language: en
font:
  name:
  path:
  size:
# menubar
menubar:
  help:
    name: "Help"
    subentries:
      about: "About"
      license: "License"
      source: "Source"
  reference:
    name: "Reference"
    subentries:
      tutorial : "Tutorial"
      paper-format: "Paper format"
      paper-fold: "Paper fold"
      unit-conversion: "Unit conversion"
  settings: 
    name: "Settings"
    subentries:
      load: "Load"
      save: "Save"
  language:
    name: "Language"
    subentries:
      en: "en" 
      kr: "kr"

# Tab in Notebook 
tabs:
  files:
    name: "Files"
    frames:
      manuscript:
        name: "Manuscript"
        strings:
          index: " "
          files: "file"
      file_info:
        name: "File Info"
        strings:
          name: "Name"
          path: "Path"
          title: "Title"
          author: "Author(s)"
          created_date: "Created Date"
          mod_date: "Modified Date"
          pages: "Pages"
          page_format: "Page Format"
      output:
        name: "Output"
        strings:
          merge: "Merge"
          total_page: "Total pages"
          name: "File name"
          as: "as"
          split_per: "Split per"
        variables:
          file_name: 
            name: "name"
            prefix: "prefix"
            suffix: "suffix"
  section:
    name: "Section"
    frames:
      standard:
        name: "Standard"
        strings:
          onoff: "On/off"
          type: "Type"
          pages_per: "Pages"
          insert: "Insert"
          paper_format: "Paper format"
          custom_format: "Custom format"
          page_range: "Page range"
          riffle_direction: "Riffle direction"
          blank_pages: "Blank pages to"
        variables:
          type:
            book: "Book"
            brochure: "Brochure"
          brochure_types:
            half-fold: "half-fold"
            tri-fold: "tri-fold"
            z-fold: "z-fold"
            gate-fold: "gate-fold"
            double-gage-fold: "double-gate-fold"
            double-parallel-fold: "double-parallel-fold"
            arcodian-fold-4: "arcodian-fold-4"
            roll-fold: "roll-fold"
          riffle_direction:
            right: "right"
            left: "left"
          blank_page:
            back: "back"
            front: "front"
            both: "both"
      custom:
        name: "Custom"
        strings:
          onoff: "On/Off"
          pages_per: "Pages per"
          layout: "Layout"
          page_order_front: "Page order front"
          fold_sequence: "Fold sequence"
          axis: "Axis"
          split: "Split"
          order: "Order"
          mv: "M/V"
          validate: "Validate"
        frames:
          layout:
            name: "Layout"
            strings:
              layout: "Layout"
              front: "Front"
          fcode:
            name: "Fcode"
            strings:
              start_axis: "Start axis"
              preview: "Preview"
              apply: "Apply"
        variables:
          type:
            lyaout: "layout"
            fcode: "fcode"
  imposition:
    name: "Imposition"
    frames:
      bookbrochures:
        name: "Book&Brochure"
        strings:
          onoff: "On/Off"
          layout: "Layout"
          collection_mark: "Collection mark"
          gap: "Gap"
          fold_line: "Fold line"
          fold_gap: "Fold gap"
          paper_thickness: "Paper thickness"
      repetition:
        name: "Repetition"
        strings:
          onoff: "On/Off"
          layout: "Layout"
          fit: "Fit"
          gap: "Gap"
          gap_line: "Gap Line"
          paper_format: "Paper format"
          page_format: "Page format"
          max_fill: "Maximum fill"
        variables:
          fit:
            to_paper: "to paper"
            to_page: "to page"
          gap_position:
            middle: "middle"
            page: "page"
          gap_type:
            plain: "_"
            dot : "..."
            dash: "_ _ _"
            dash_dot: "_._._"
  printingmarks:
      name: "Printing Marks"
      frames:
        printingmarks:
          name: "Marks"
          strings:
            margin: "Margin"
            crop: "Crop"
            trim: "Trim"
            reg: "Registration"
            cmyk: "CMYK"
            direction: "Direction"
            angle: "Angle"
            duplex: "Duplex meausre"
  utils:
      name: "Utils"
      frames:
        toimage:
          name: "To image"
          strings:
            onoff: "On/Off"
        duplex:
          name: "Duplex"
          strings:
            onoff: "On/Off"
            translation: "Translation"
            rotation: "Rotation"
            preserve:  "Preserve dim"
        note:
          name: "Note"
          strings:
            onoff: "On/Off"
            pages: "Pages"
          frames:
            numbering: 
              name: "Numbering"
              strings:
                onoff: "On/Off"
                count: "Count"
                mark_on: "Mark on"
                location: "Location"
                align: "Align"
                font: "Font"
                size: "Size"
              variables:
                count: 
                  both: "both"
                  odd: "odd"
                  even: "even"
                  oddo : "odd(only)"
                  eveno: "even(only)"
                mark_on:
                  both: "both"
                  odd: "odd"
                  even: "even"
                location:
                  header: "header"
                  footer: "footer"
                  hf: "hf"
                  fh: "fh"
                align:
                  left: "left"
                  right: "right"
                  center: "center"
                  lr: "lr"
                  rl: "rl"
                  lc: "lc"
                  cl: "cl"
                  rc: "rc"
                  cr: "cr"
# Misc UI

generate: "Generate"
