# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  #jobs:
  #  pre_create_environment:
  #    - echo "Command run at 'pre_create_environment' step"
  #    - pip install sphinxawesome_theme
  commands:
    - python -mvirtualenv /home/docs/checkouts/readthedocs.org/user_builds/booklet/envs/latest
    - /home/docs/checkouts/readthedocs.org/user_builds/booklet/envs/latest/bin/python -m pip install --upgrade --no-cache-dir pip setuptools<58.3.0 
    - /home/docs/checkouts/readthedocs.org/user_builds/booklet/envs/latest/bin/python -m pip install --upgrade --no-cache-dir mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx sphinxawesome_theme readthedocs-sphinx-ext<2.2 
    - /home/docs/checkouts/readthedocs.org/user_builds/booklet/envs/latest/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: documents/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
#python:
#   install:
#   - requirements: docs/requirements.txt
